name: Deploy Prefect flow

on:
  push:
    branches:
      - main
    paths:
      - 'prefect_deploy/prefect.yml'
      - 'register_prefect_flow.py'
  workflow_dispatch:
  repository_dispatch:
    types: [custom-event]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Prefect Deploy
        env:
          PREFECT_API_KEY: MIIEpAIBAAKCAQEApweCZ9iueMNrV1fQCNnbJ8f4DfJVSeelUVKx3kkODDp0aveN
          PREFECT_API_URL: http://16.171.4.29:80/api 
        run: |
          pip install prefect
          prefect deploy --prefect-file prefect_deploy/prefect.yml --all